#!/usr/bin/env bash
# scripts/engine/lib.sh — shared helpers for install.sh / rollback.sh / status.sh.
#
# Layout assumptions (SPA-6060, ENGINE-MIGRATE leaf 4), all overridable via env
# for local dry-run testing:
#
#   ENGINE_ROOT           default: /home/jamesilsley
#   PAPERCLIP_HOME         default: $ENGINE_ROOT/.paperclip-831
#                          — this is the CLI's own PAPERCLIP_HOME env var
#                          (packages/shared/src/home-paths.ts resolvePaperclipHomeDir():
#                          `process.env.PAPERCLIP_HOME`, falls back to ~/.paperclip).
#   PAPERCLIP_INSTANCE_ID  default: default
#                          — the CLI's own instance id env var (same file,
#                          resolvePaperclipInstanceId()). Real instance state
#                          (config.json, db/, logs/, secrets/) lives at
#                          $PAPERCLIP_HOME/instances/$PAPERCLIP_INSTANCE_ID/
#                          (resolvePaperclipInstanceRoot()) — NOT directly at
#                          $PAPERCLIP_HOME. The handoff assumed the instance
#                          dir *was* PAPERCLIP_HOME; that is not how the CLI
#                          resolves it, so this file documents the real path
#                          and everything below derives from it.
#   CURRENT_LINK           default: $ENGINE_ROOT/paperclip-current
#   UNIT_NAME              default: paperclip-831.service
#                          NOTE: the CLI's own `paperclipai service install`
#                          command (cli/src/services/service-manager.ts
#                          systemdServiceName()) would name this unit
#                          `paperclipai.service` (instance "default") or
#                          `paperclipai-<id>.service`. `paperclip-831.service`
#                          is our own ops-layer naming per the handoff, laid
#                          on top of — not generated by — the CLI's mechanism.
#                          status.sh lists all `paperclip*` units so a mismatch
#                          with whatever leaf 2 actually installed is visible,
#                          not silently assumed.
#   EXPECTED_DB             default: paperclip831 (safety guard, see below)
#   BACKUP_DIR              default: $ENGINE_ROOT/paperclip-backups
#   STATE_DIR               default: $ENGINE_ROOT/.paperclip-engine
#   HEALTH_TIMEOUT_SECS      default: 90
#   HEALTH_POLL_SECS         default: 2
#
# The systemd unit's ExecStart is
#   "$CURRENT_LINK/bin/paperclipai" run --instance "$PAPERCLIP_INSTANCE_ID"
# — i.e. it goes through the npm `-g --prefix` bin shim inside the *symlink*,
# not a hardcoded dist/index.js path in a specific version prefix. That is
# what makes "flip the symlink, restart the unit" a real cutover. See
# scripts/engine/systemd/paperclip-831.service, cited from
# cli/src/services/service-manager.ts renderSystemdUnit() (Type=notify,
# NotifyAccess=all, the three Environment= lines, Restart=always,
# RestartSec=5, TimeoutStopSec=300 are all copied from there — the server
# really does call sd_notify, see server/src/services/systemd-notify.ts and
# server/src/index.ts import of it).
#
# Health endpoint: GET /api/health (server/src/app.ts: `app.use("/api", api)`
# + `api.use("/health", healthRoutes(...))`; cli/src/utils/health-url.ts
# buildLocalHealthUrl() builds exactly this path). Body has a `status` field
# (== "ok" when healthy) and `version`/`serverVersion`.
#
# Migration table: "drizzle"."__drizzle_migrations" (packages/db/src/client.ts
# DRIZZLE_MIGRATIONS_TABLE).
#
# PAPERCLIP_ENGINE_DRY_RUN=1 — every external mutating command (npm, pnpm,
# git/curl fetch, systemctl, pg_dump, pg_restore, corepack) is logged and NOT
# executed; the install functions instead synthesize a minimal but
# structurally valid fake prefix (package.json + bin/paperclipai shim) so the
# surrounding orchestration (symlink flip, health wait, rollback-on-failure)
# can be exercised end to end without a real build or network access. See
# scripts/engine/tests/.

set -euo pipefail

# ---------------------------------------------------------------------------
# Paths / config (all overridable)
# ---------------------------------------------------------------------------

ENGINE_ROOT="${ENGINE_ROOT:-/home/jamesilsley}"
PAPERCLIP_HOME="${PAPERCLIP_HOME:-$ENGINE_ROOT/.paperclip-831}"
PAPERCLIP_INSTANCE_ID="${PAPERCLIP_INSTANCE_ID:-default}"
CURRENT_LINK="${CURRENT_LINK:-$ENGINE_ROOT/paperclip-current}"
UNIT_NAME="${UNIT_NAME:-paperclip-831.service}"
EXPECTED_DB="${EXPECTED_DB:-paperclip831}"
BACKUP_DIR="${BACKUP_DIR:-$ENGINE_ROOT/paperclip-backups}"
STATE_DIR="${STATE_DIR:-$ENGINE_ROOT/.paperclip-engine}"
HEALTH_TIMEOUT_SECS="${HEALTH_TIMEOUT_SECS:-90}"
HEALTH_POLL_SECS="${HEALTH_POLL_SECS:-2}"
MIN_FREE_KB="${MIN_FREE_KB:-2097152}" # 2GiB

# Local git source used to resolve/clone a `fork:<ref>` install. Defaults to
# the repo this script itself lives in. On bigbox, point this at whatever
# persistent checkout/mirror of Spark-Mojo/paperclip exists there — this
# script deliberately resolves refs from a local git object store (no GitHub
# API call), so the ref must already be fetched into that source repo.
FORK_SOURCE_REPO="${FORK_SOURCE_REPO:-}"

INSTANCE_ROOT="$PAPERCLIP_HOME/instances/$PAPERCLIP_INSTANCE_ID"
INSTANCE_CONFIG="$INSTANCE_ROOT/config.json"
PREVIOUS_STATE_FILE="$STATE_DIR/previous-prefix"

DRY_RUN="${PAPERCLIP_ENGINE_DRY_RUN:-0}"

# ---------------------------------------------------------------------------
# Logging
# ---------------------------------------------------------------------------

log() {
  printf '[%s] %s\n' "$(date -u +%Y-%m-%dT%H:%M:%SZ)" "$*" >&2
}

die() {
  log "ERROR: $*"
  exit 1
}

# Runs (and logs) an external command. In dry-run mode it logs the command
# with a "+DRYRUN " prefix and does not execute it (exit 0). Callers that
# need dry-run behavior to still produce usable state must not rely solely on
# `run` — see stage_fake_payload() in install.sh.
run() {
  if [ "$DRY_RUN" = "1" ]; then
    log "+DRYRUN $*"
    return 0
  fi
  log "+ $*"
  "$@"
}

# ---------------------------------------------------------------------------
# Guards
# ---------------------------------------------------------------------------

# Refuse to run against a live host unless it looks like the intended target,
# or we are explicitly in a sandboxed dry-run test.
guard_host() {
  if [ "$DRY_RUN" = "1" ]; then
    return 0
  fi
  local os
  os="$(uname -s)"
  if [ "$os" != "Linux" ]; then
    die "This script targets Linux (bigbox). Refusing to run on '$os' outside PAPERCLIP_ENGINE_DRY_RUN=1. Never point it at the laptop's live paperclip."
  fi
}

# Refuse to touch a database that isn't the expected local instance DB. Reads
# database.connectionString / database.mode out of the *currently active*
# instance config (if any) via node — never sed/grep on a URI.
assert_expected_database() {
  local config_path="$1"
  if [ ! -f "$config_path" ]; then
    log "No existing instance config at $config_path yet (first install) — skipping database identity guard."
    return 0
  fi
  local info
  info="$(node -e '
    const fs = require("fs");
    const cfg = JSON.parse(fs.readFileSync(process.argv[1], "utf8"));
    const db = cfg.database || {};
    if (db.mode !== "postgres" || !db.connectionString) {
      console.log("SKIP");
      process.exit(0);
    }
    const u = new URL(db.connectionString);
    console.log([u.hostname, (u.pathname || "").replace(/^\//, "")].join(" "));
  ' "$config_path")"
  if [ "$info" = "SKIP" ]; then
    log "Instance is not in postgres mode (or has no connectionString) — skipping database identity guard."
    return 0
  fi
  local host db_name
  host="$(echo "$info" | awk '{print $1}')"
  db_name="$(echo "$info" | awk '{print $2}')"
  case "$host" in
    127.0.0.1|localhost) ;;
    *) die "Refusing to operate: instance database host '$host' is not 127.0.0.1/localhost. This script only manages the local bigbox instance." ;;
  esac
  if [ "$db_name" != "$EXPECTED_DB" ]; then
    die "Refusing to operate: instance database name '$db_name' != expected '$EXPECTED_DB'. Set EXPECTED_DB if this is intentional."
  fi
}

connection_string_from_config() {
  local config_path="$1"
  node -e '
    const fs = require("fs");
    const cfg = JSON.parse(fs.readFileSync(process.argv[1], "utf8"));
    const db = cfg.database || {};
    if (db.mode !== "postgres" || !db.connectionString) { process.exit(1); }
    process.stdout.write(db.connectionString);
  ' "$config_path"
}

server_port_from_config() {
  local config_path="$1"
  node -e '
    const fs = require("fs");
    const cfg = JSON.parse(fs.readFileSync(process.argv[1], "utf8"));
    process.stdout.write(String((cfg.server && cfg.server.port) || 3100));
  ' "$config_path"
}

server_host_from_config() {
  local config_path="$1"
  node -e '
    const fs = require("fs");
    const cfg = JSON.parse(fs.readFileSync(process.argv[1], "utf8"));
    process.stdout.write((cfg.server && cfg.server.host) || "127.0.0.1");
  ' "$config_path"
}

# Mirrors cli/src/utils/health-url.ts buildLocalHealthUrl().
health_url() {
  local config_path="$1"
  local host port
  host="$(server_host_from_config "$config_path")"
  port="$(server_port_from_config "$config_path")"
  case "$host" in
    ""|0.0.0.0|::) host="127.0.0.1" ;;
  esac
  echo "http://$host:$port/api/health"
}

# ---------------------------------------------------------------------------
# Version / prefix helpers
# ---------------------------------------------------------------------------

prefix_version() {
  local prefix="$1"
  local pkg="$prefix/lib/node_modules/paperclipai/package.json"
  if [ ! -f "$pkg" ]; then
    die "No paperclipai package.json found at $pkg — prefix $prefix does not look installed."
  fi
  node -e 'console.log(JSON.parse(require("fs").readFileSync(process.argv[1], "utf8")).version)' "$pkg"
}

# Best-effort: locate the packed @paperclipai/server inside a prefix, to
# prove a fork install did not silently fall back to a registry server
# package. Not fatal if not found (layout can vary with npm's hoisting).
prefix_server_package_path() {
  local prefix="$1"
  find "$prefix/lib/node_modules" -maxdepth 4 -path '*/@paperclipai/server/package.json' 2>/dev/null | head -1
}

current_target() {
  if [ -L "$CURRENT_LINK" ]; then
    readlink "$CURRENT_LINK"
  else
    echo ""
  fi
}

record_previous_target() {
  local target="$1"
  mkdir -p "$STATE_DIR"
  if [ -n "$target" ]; then
    printf '%s\n' "$target" > "$PREVIOUS_STATE_FILE"
    log "Recorded previous prefix for rollback: $target"
  fi
}

read_previous_target() {
  if [ -f "$PREVIOUS_STATE_FILE" ]; then
    cat "$PREVIOUS_STATE_FILE"
  else
    echo ""
  fi
}

flip_symlink() {
  local target="$1"
  # Always a real filesystem operation, even under PAPERCLIP_ENGINE_DRY_RUN=1
  # — it is local, cheap, and it IS the state this script (and its tests)
  # exist to exercise; unlike npm/git/systemctl/pg_dump it is never stubbed.
  # ln -sfn atomically replaces an existing symlink (rename() under the
  # hood) on both GNU and BSD/macOS ln — unlike `mv`, which has the
  # well-known "moves INTO an existing symlink-to-directory" gotcha.
  log "+ ln -sfn $target $CURRENT_LINK"
  ln -sfn "$target" "$CURRENT_LINK"
}

# ---------------------------------------------------------------------------
# systemd
# ---------------------------------------------------------------------------

unit_stop() {
  run systemctl --user stop "$UNIT_NAME" || true
}

# Returns non-zero (does not `die`) if the unit fails to reach "started" —
# with Type=notify this call blocks until sd_notify(READY=1) or a timeout,
# so a broken new version legitimately makes this fail. Callers MUST check
# the return value themselves (never call this bare under `set -e` and
# expect to reach a rollback branch afterwards — a non-zero exit here would
# otherwise abort the whole script before rollback logic runs).
#
# PAPERCLIP_ENGINE_TEST_FAIL_START=1 forces a synthetic failure, for tests
# that need to exercise the rollback path without a real unit.
unit_start() {
  if [ "${PAPERCLIP_ENGINE_TEST_FAIL_START:-0}" = "1" ]; then
    log "+TESTHOOK simulating systemctl start failure (PAPERCLIP_ENGINE_TEST_FAIL_START=1)"
    return 1
  fi
  run systemctl --user start "$UNIT_NAME"
}

unit_restart() {
  run systemctl --user restart "$UNIT_NAME"
}

# Refuses to silently overwrite a unit file that already exists with
# different content — another operator/script (e.g. leaf 2's own install)
# may have put a different ExecStart there. Set
# PAPERCLIP_ENGINE_REPLACE_UNIT=1 to allow an intentional overwrite. A
# missing unit file is always installed (first run is not a conflict).
unit_ensure_installed() {
  local unit_path="$HOME/.config/systemd/user/$UNIT_NAME"
  local template="$1"
  if [ "$DRY_RUN" = "1" ]; then
    log "+DRYRUN would ensure unit file at $unit_path from $template"
    return 0
  fi
  mkdir -p "$(dirname "$unit_path")"
  if [ ! -f "$unit_path" ]; then
    log "Installing unit file $unit_path"
    cp "$template" "$unit_path"
    run systemctl --user daemon-reload
    return 0
  fi
  if ! cmp -s "$template" "$unit_path"; then
    if [ "${PAPERCLIP_ENGINE_REPLACE_UNIT:-0}" != "1" ]; then
      log "Existing unit file $unit_path differs from $template:"
      diff -u "$unit_path" "$template" >&2 || true
      die "Refusing to overwrite an existing, different unit file. Review the diff above; set PAPERCLIP_ENGINE_REPLACE_UNIT=1 to replace it deliberately."
    fi
    log "Replacing unit file $unit_path (PAPERCLIP_ENGINE_REPLACE_UNIT=1)"
    cp "$template" "$unit_path"
    run systemctl --user daemon-reload
  fi
}

# ---------------------------------------------------------------------------
# Health
# ---------------------------------------------------------------------------

# Polls GET <url>; returns 0 and prints the JSON body on success (HTTP 2xx and
# body.status == "ok"), returns 1 after HEALTH_TIMEOUT_SECS otherwise.
wait_for_health() {
  local url="$1"
  local deadline=$(( $(date +%s) + HEALTH_TIMEOUT_SECS ))
  local body
  while [ "$(date +%s)" -lt "$deadline" ]; do
    if body="$(curl -fsS -m 5 "$url" 2>/dev/null)"; then
      if node -e '
          let input = "";
          process.stdin.on("data", (d) => (input += d));
          process.stdin.on("end", () => {
            try {
              const parsed = JSON.parse(input);
              process.exit(parsed.status === "ok" ? 0 : 1);
            } catch {
              process.exit(1);
            }
          });
        ' <<<"$body"; then
        echo "$body"
        return 0
      fi
    fi
    sleep "$HEALTH_POLL_SECS"
  done
  return 1
}

# ---------------------------------------------------------------------------
# Database
# ---------------------------------------------------------------------------

migration_count() {
  local connection_string="$1"
  if [ "$DRY_RUN" = "1" ]; then
    echo "0"
    return 0
  fi
  psql "$connection_string" -tAc 'select count(*) from "drizzle"."__drizzle_migrations"' 2>/dev/null | tr -d ' '
}

agents_paused_count() {
  local connection_string="$1"
  if [ "$DRY_RUN" = "1" ]; then
    echo "0"
    return 0
  fi
  # agents.status = 'paused' is the canonical signal the server itself
  # checks (server/src/routes/companies.ts, agents.ts, issues.ts all query
  # eq(agentsTable.status, "paused")) — not paused_at, which the schema
  # (packages/db/src/schema/agents.ts) only documents as "when", not as the
  # source of truth for whether an agent is currently paused.
  psql "$connection_string" -tAc "select count(*) from agents where status = 'paused'" 2>/dev/null | tr -d ' '
}

backup_database() {
  local connection_string="$1"
  local label="$2"
  mkdir -p "$BACKUP_DIR"
  local ts
  ts="$(date -u +%Y%m%dT%H%M%SZ)"
  local dump_path="$BACKUP_DIR/${ts}-${label}.dump"
  run pg_dump -Fc "$connection_string" -f "$dump_path"
  echo "$dump_path"
}
