#!/usr/bin/env bash
# scripts/engine/lib.sh — shared helpers for install.sh / rollback.sh / status.sh.
#
# Layout assumptions (SPA-6060, ENGINE-MIGRATE leaf 4), all overridable via env
# for local dry-run testing:
#
#   ENGINE_ROOT           default: /home/jamesilsley
#   PAPERCLIP_HOME         default: $ENGINE_ROOT/.paperclip-831
#                          — this is the CLI's own PAPERCLIP_HOME env var
#                          (packages/shared/src/home-paths.ts resolvePaperclipHomeDir():
#                          `process.env.PAPERCLIP_HOME`, falls back to ~/.paperclip).
#   PAPERCLIP_INSTANCE_ID  default: default
#                          — the CLI's own instance id env var (same file,
#                          resolvePaperclipInstanceId()). Real instance state
#                          (config.json, db/, logs/, secrets/) lives at
#                          $PAPERCLIP_HOME/instances/$PAPERCLIP_INSTANCE_ID/
#                          (resolvePaperclipInstanceRoot()) — NOT directly at
#                          $PAPERCLIP_HOME. The handoff assumed the instance
#                          dir *was* PAPERCLIP_HOME; that is not how the CLI
#                          resolves it, so this file documents the real path
#                          and everything below derives from it.
#   CURRENT_LINK           default: $ENGINE_ROOT/paperclip-current
#   UNIT_NAME              default: paperclip-831.service
#                          NOTE: the CLI's own `paperclipai service install`
#                          command (cli/src/services/service-manager.ts
#                          systemdServiceName()) would name this unit
#                          `paperclipai.service` (instance "default") or
#                          `paperclipai-<id>.service`. `paperclip-831.service`
#                          is our own ops-layer naming per the handoff, laid
#                          on top of — not generated by — the CLI's mechanism.
#                          status.sh lists all `paperclip*` units so a mismatch
#                          with whatever leaf 2 actually installed is visible,
#                          not silently assumed.
#   EXPECTED_DB             default: paperclip831 (safety guard, see below)
#   BACKUP_DIR              default: $ENGINE_ROOT/paperclip-backups
#   STATE_DIR               default: $ENGINE_ROOT/.paperclip-engine
#   HEALTH_TIMEOUT_SECS      default: 90
#   HEALTH_POLL_SECS         default: 2
#   PAPERCLIP_ENGINE_ADOPT_EXISTING_PREFIX
#                            opt-in absolute npm prefix already serving the
#                            instance (for bigbox, /usr). Seeds CURRENT_LINK
#                            to that prefix and redirects the existing unit
#                            with one managed ExecStart-only drop-in.
#
# The systemd unit's ExecStart is
#   "$CURRENT_LINK/bin/paperclipai" run --instance "$PAPERCLIP_INSTANCE_ID"
# — i.e. it goes through the npm `-g --prefix` bin shim inside the *symlink*,
# not a hardcoded dist/index.js path in a specific version prefix. That is
# what makes "flip the symlink, restart the unit" a real cutover. See
# scripts/engine/systemd/paperclip-831.service, cited from
# cli/src/services/service-manager.ts renderSystemdUnit() (Type=notify,
# NotifyAccess=all, the three Environment= lines, Restart=always,
# RestartSec=5, TimeoutStopSec=300 are all copied from there — the server
# really does call sd_notify, see server/src/services/systemd-notify.ts and
# server/src/index.ts import of it).
#
# Health endpoint: GET /api/health (server/src/app.ts: `app.use("/api", api)`
# + `api.use("/health", healthRoutes(...))`; cli/src/utils/health-url.ts
# buildLocalHealthUrl() builds exactly this path). Body has a `status` field
# (== "ok" when healthy) and `version`/`serverVersion`.
#
# Migration table: "drizzle"."__drizzle_migrations" (packages/db/src/client.ts
# DRIZZLE_MIGRATIONS_TABLE).
#
# PAPERCLIP_ENGINE_DRY_RUN=1 — every external mutating command (npm, pnpm,
# git/curl fetch, systemctl, pg_dump, pg_restore, corepack) is logged and NOT
# executed; the install functions instead synthesize a minimal but
# structurally valid fake prefix (package.json + bin/paperclipai shim) so the
# surrounding orchestration (symlink flip, health wait, rollback-on-failure)
# can be exercised end to end without a real build or network access. See
# scripts/engine/tests/.

set -euo pipefail

# ---------------------------------------------------------------------------
# Paths / config (all overridable)
# ---------------------------------------------------------------------------

ENGINE_ROOT="${ENGINE_ROOT:-/home/jamesilsley}"
PAPERCLIP_HOME="${PAPERCLIP_HOME:-$ENGINE_ROOT/.paperclip-831}"
PAPERCLIP_INSTANCE_ID="${PAPERCLIP_INSTANCE_ID:-default}"
CURRENT_LINK="${CURRENT_LINK:-$ENGINE_ROOT/paperclip-current}"
UNIT_NAME="${UNIT_NAME:-paperclip-831.service}"
EXPECTED_DB="${EXPECTED_DB:-paperclip831}"
BACKUP_DIR="${BACKUP_DIR:-$ENGINE_ROOT/paperclip-backups}"
STATE_DIR="${STATE_DIR:-$ENGINE_ROOT/.paperclip-engine}"
HEALTH_TIMEOUT_SECS="${HEALTH_TIMEOUT_SECS:-90}"
HEALTH_POLL_SECS="${HEALTH_POLL_SECS:-2}"
MIN_FREE_KB="${MIN_FREE_KB:-2097152}" # 2GiB
PAPERCLIP_ENGINE_ADOPT_EXISTING_PREFIX="${PAPERCLIP_ENGINE_ADOPT_EXISTING_PREFIX:-}"
ADOPTION_DROPIN_NAME="zzzz-paperclip-engine-current.conf"

# Local git source used to resolve/clone a `fork:<ref>` install. Defaults to
# the repo this script itself lives in. On bigbox, point this at whatever
# persistent checkout/mirror of Spark-Mojo/paperclip exists there — this
# script deliberately resolves refs from a local git object store (no GitHub
# API call), so the ref must already be fetched into that source repo.
FORK_SOURCE_REPO="${FORK_SOURCE_REPO:-}"

INSTANCE_ROOT="$PAPERCLIP_HOME/instances/$PAPERCLIP_INSTANCE_ID"
INSTANCE_CONFIG="$INSTANCE_ROOT/config.json"
PREVIOUS_STATE_FILE="$STATE_DIR/previous-prefix"

DRY_RUN="${PAPERCLIP_ENGINE_DRY_RUN:-0}"

# ---------------------------------------------------------------------------
# Logging
# ---------------------------------------------------------------------------

log() {
  printf '[%s] %s\n' "$(date -u +%Y-%m-%dT%H:%M:%SZ)" "$*" >&2
}

die() {
  log "ERROR: $*"
  exit 1
}

# Runs (and logs) an external command. In dry-run mode it logs the command
# with a "+DRYRUN " prefix and does not execute it (exit 0). Callers that
# need dry-run behavior to still produce usable state must not rely solely on
# `run` — see stage_fake_payload() in install.sh.
run() {
  if [ "$DRY_RUN" = "1" ]; then
    log "+DRYRUN $*"
    return 0
  fi
  log "+ $*"
  "$@"
}

prepare_pnpm_toolchain() {
  local staging_root="$1"
  local install_dir="$staging_root/pnpm-bin"
  mkdir -p "$install_dir"
  run corepack enable pnpm --install-directory "$install_dir"
}

install_whats_running() {
  local destination="${PAPERCLIP_WHATS_RUNNING_PATH:-$HOME/bin/whats-running}"
  local bundle_root="$HOME/.local/lib/paperclip-engine-runtime" staging bundle_id bundle link_tmp
  mkdir -p "$(dirname "$destination")" "$bundle_root"
  staging="$(mktemp -d "$bundle_root/.staging.XXXXXX")"
  trap 'rm -rf "$staging" "${link_tmp:-}"' RETURN
  cp "$SCRIPT_DIR/whats-running.sh" "$SCRIPT_DIR/overlay-contract.mjs" "$staging/"
  chmod 0755 "$staging/whats-running.sh" "$staging/overlay-contract.mjs"
  bash -n "$staging/whats-running.sh"; node --check "$staging/overlay-contract.mjs"
  bundle_id="$(cat "$staging/whats-running.sh" "$staging/overlay-contract.mjs" | sha256sum | awk '{print $1}')"
  bundle="$bundle_root/$bundle_id"
  if [ ! -d "$bundle" ]; then
    mv "$staging" "$bundle"
  else
    if ! node -e '
      const fs=require("fs"),path=require("path"),crypto=require("crypto");
      const expected=["overlay-contract.mjs","whats-running.sh"];
      function check(root){const names=fs.readdirSync(root).sort();if(JSON.stringify(names)!==JSON.stringify(expected))process.exit(1);return names.map(n=>{const p=path.join(root,n),s=fs.lstatSync(p);if(!s.isFile()||s.isSymbolicLink()||(s.mode&0o777)!==0o755)process.exit(1);return crypto.createHash("sha256").update(fs.readFileSync(p)).digest("hex")})}
      if(JSON.stringify(check(process.argv[1]))!==JSON.stringify(check(process.argv[2])))process.exit(1);
    ' "$staging" "$bundle"; then
      die "Existing reporter bundle failed exact inventory verification."
    fi
    rm -rf "$staging"
  fi
  if [ "${PAPERCLIP_ENGINE_TEST_FAIL_REPORT_INSTALL:-0}" = "1" ]; then die "Injected runtime report installation failure before atomic link flip."; fi
  link_tmp="$(dirname "$destination")/.whats-running.$$"
  ln -s "$bundle/whats-running.sh" "$link_tmp"
  mv -Tf "$link_tmp" "$destination"
  trap - RETURN
  log "Installed managed runtime report at $destination"
}

install_fork_payload() {
  local prefix="$1"
  shift
  run npm install --global --prefix "$prefix" "$@" --no-audit --no-fund
}

install_npm_payload() {
  local prefix="$1" version="$2"
  run npm install --global --prefix "$prefix" "paperclipai@$version" \
    --registry=https://registry.npmjs.org \
    "--@paperclipai:registry=https://registry.npmjs.org" \
    --no-audit --no-fund
}

assert_fork_rust_toolchain() {
  local source_repo="$1"
  local toolchain_dir="$source_repo/packages/paperclip-runner"
  local toolchain_file="$toolchain_dir/rust-toolchain.toml"
  [ -f "$toolchain_file" ] || die "Fork runner toolchain file is missing: $toolchain_file"
  local required cargo_version rustc_version
  required="$(sed -n 's/^[[:space:]]*channel[[:space:]]*=[[:space:]]*"\([^"]*\)".*/\1/p' "$toolchain_file")"
  [ -n "$required" ] || die "Cannot read pinned Rust version from $toolchain_file"
  command -v cargo >/dev/null 2>&1 || die "Fork build requires Cargo from pinned Rust $required before topology adoption or backup."
  command -v rustc >/dev/null 2>&1 || die "Fork build requires rustc from pinned Rust $required before topology adoption or backup."
  cargo_version="$(cd "$toolchain_dir" && cargo --version 2>/dev/null | awk '{print $2}')" || true
  rustc_version="$(cd "$toolchain_dir" && rustc --version 2>/dev/null | awk '{print $2}')" || true
  if [ "$cargo_version" != "$required" ] || [ "$rustc_version" != "$required" ]; then
    die "Fork build requires pinned Rust $required; found cargo ${cargo_version:-unavailable} and rustc ${rustc_version:-unavailable}."
  fi
  log "Preflight: pinned Rust $required available"
}

# ---------------------------------------------------------------------------
# Guards
# ---------------------------------------------------------------------------

# Refuse to run against a live host unless it looks like the intended target,
# or we are explicitly in a sandboxed dry-run test.
guard_host() {
  if [ "$DRY_RUN" = "1" ]; then
    return 0
  fi
  local os
  os="$(uname -s)"
  if [ "$os" != "Linux" ]; then
    die "This script targets Linux (bigbox). Refusing to run on '$os' outside PAPERCLIP_ENGINE_DRY_RUN=1. Never point it at the laptop's live paperclip."
  fi
}

# Refuse to touch a database that isn't the expected local instance DB. Reads
# database.connectionString / database.mode out of the *currently active*
# instance config (if any) via node — never sed/grep on a URI.
assert_expected_database() {
  local config_path="$1"
  if [ ! -f "$config_path" ]; then
    log "No existing instance config at $config_path yet (first install) — skipping database identity guard."
    return 0
  fi
  local info
  info="$(node -e '
    const fs = require("fs");
    const cfg = JSON.parse(fs.readFileSync(process.argv[1], "utf8"));
    const db = cfg.database || {};
    if (db.mode !== "postgres" || !db.connectionString) {
      console.log("SKIP");
      process.exit(0);
    }
    const u = new URL(db.connectionString);
    console.log([u.hostname, (u.pathname || "").replace(/^\//, "")].join(" "));
  ' "$config_path")"
  if [ "$info" = "SKIP" ]; then
    log "Instance is not in postgres mode (or has no connectionString) — skipping database identity guard."
    return 0
  fi
  local host db_name
  host="$(echo "$info" | awk '{print $1}')"
  db_name="$(echo "$info" | awk '{print $2}')"
  case "$host" in
    127.0.0.1|localhost) ;;
    *) die "Refusing to operate: instance database host '$host' is not 127.0.0.1/localhost. This script only manages the local bigbox instance." ;;
  esac
  if [ "$db_name" != "$EXPECTED_DB" ]; then
    die "Refusing to operate: instance database name '$db_name' != expected '$EXPECTED_DB'. Set EXPECTED_DB if this is intentional."
  fi
}

connection_string_from_config() {
  local config_path="$1"
  node -e '
    const fs = require("fs");
    const cfg = JSON.parse(fs.readFileSync(process.argv[1], "utf8"));
    const db = cfg.database || {};
    if (db.mode !== "postgres" || !db.connectionString) { process.exit(1); }
    process.stdout.write(db.connectionString);
  ' "$config_path"
}

# Run a libpq client without placing the connection URI or password in its
# argv, environment, or logs. Credentials live only in temporary mode-0600
# libpq files inside a mode-0700 directory and are removed on every exit.
secure_database_command() (
  local connection_string="$1"
  shift
  local credential_dir service_file pass_file
  credential_dir="$(mktemp -d "${TMPDIR:-/tmp}/paperclip-db.XXXXXX")"
  chmod 0700 "$credential_dir"
  service_file="$credential_dir/pg_service.conf"
  pass_file="$credential_dir/pgpass"
  trap 'rm -rf "$credential_dir"' EXIT
  trap 'exit 129' HUP
  trap 'exit 130' INT
  trap 'exit 143' TERM

  if ! printf '%s' "$connection_string" | node -e '
    const fs = require("fs");
    let raw = "";
    process.stdin.on("data", chunk => raw += chunk);
    process.stdin.on("end", () => {
      try {
        const uri = new URL(raw);
        if (!['"'"'postgres:'"'"', '"'"'postgresql:'"'"'].includes(uri.protocol)) throw new Error();
        if (!uri.hostname || !uri.pathname || uri.pathname === "/") throw new Error();
        const allowed = new Set([
          "application_name", "channel_binding", "connect_timeout", "gssencmode",
          "keepalives", "keepalives_count", "keepalives_idle", "keepalives_interval",
          "options", "sslcert", "sslcrl", "sslcrldir", "sslkey", "sslmode",
          "sslrootcert", "target_session_attrs", "tcp_user_timeout"
        ]);
        const options = [];
        for (const [key, value] of uri.searchParams) {
          if (!allowed.has(key)) {
            process.stderr.write(`Unsupported PostgreSQL connection option: ${key}\n`);
            process.exit(2);
          }
          if (options.some(([seen]) => seen === key)) throw new Error();
          options.push([key, value]);
        }
        const fields = {
          host: uri.hostname,
          port: uri.port || "5432",
          dbname: decodeURIComponent(uri.pathname.slice(1)),
          user: decodeURIComponent(uri.username)
        };
        for (const value of [...Object.values(fields), ...options.map(([, value]) => value)]) {
          if (/[\r\n]/.test(value)) throw new Error();
        }
        const service = ["[paperclip_engine]", ...Object.entries(fields).map(([k, v]) => `${k}=${v}`), ...options.map(([k, v]) => `${k}=${v}`), ""].join("\n");
        const pgpassEscape = value => value.replace(/\\/g, "\\\\").replace(/:/g, "\\:");
        const password = decodeURIComponent(uri.password);
        if (/[\r\n]/.test(password)) throw new Error();
        const pass = [fields.host, fields.port, fields.dbname, fields.user, password].map(pgpassEscape).join(":") + "\n";
        fs.writeFileSync(process.argv[1], service, { mode: 0o600 });
        fs.writeFileSync(process.argv[2], pass, { mode: 0o600 });
        fs.chmodSync(process.argv[1], 0o600);
        fs.chmodSync(process.argv[2], 0o600);
      } catch {
        process.stderr.write("Invalid or unsupported PostgreSQL connection URI.\n");
        process.exit(2);
      }
    });
  ' "$service_file" "$pass_file"; then
    die "Cannot create temporary libpq credentials from instance configuration."
  fi

  export PGSERVICE=paperclip_engine
  export PGSERVICEFILE="$service_file"
  export PGPASSFILE="$pass_file"
  run "$@"
)

database_reachable() {
  secure_database_command "$1" psql -tAc 'select 1'
}

server_port_from_config() {
  local config_path="$1"
  node -e '
    const fs = require("fs");
    const cfg = JSON.parse(fs.readFileSync(process.argv[1], "utf8"));
    process.stdout.write(String((cfg.server && cfg.server.port) || 3100));
  ' "$config_path"
}

server_host_from_config() {
  local config_path="$1"
  node -e '
    const fs = require("fs");
    const cfg = JSON.parse(fs.readFileSync(process.argv[1], "utf8"));
    process.stdout.write((cfg.server && cfg.server.host) || "127.0.0.1");
  ' "$config_path"
}

# Mirrors cli/src/utils/health-url.ts buildLocalHealthUrl().
health_url() {
  local config_path="$1"
  local host port
  host="$(server_host_from_config "$config_path")"
  port="$(server_port_from_config "$config_path")"
  case "$host" in
    ""|0.0.0.0|::) host="127.0.0.1" ;;
  esac
  echo "http://$host:$port/api/health"
}

# ---------------------------------------------------------------------------
# Version / prefix helpers
# ---------------------------------------------------------------------------

prefix_version() {
  local prefix="$1"
  local pkg="$prefix/lib/node_modules/paperclipai/package.json"
  if [ ! -f "$pkg" ]; then
    die "No paperclipai package.json found at $pkg — prefix $prefix does not look installed."
  fi
  node -e 'console.log(JSON.parse(require("fs").readFileSync(process.argv[1], "utf8")).version)' "$pkg"
}

# Locate @paperclipai/server in npm layouts used by Paperclip installs.
prefix_server_package_path() {
  local prefix="$1"
  local candidate
  for candidate in \
    "$prefix/lib/node_modules/@paperclipai/server/package.json" \
    "$prefix/lib/node_modules/paperclipai/node_modules/@paperclipai/server/package.json"; do
    if [ -f "$candidate" ]; then
      printf '%s\n' "$candidate"
      return 0
    fi
  done
  return 1
}

package_name_from_tarball() {
  local tarball="$1"
  tar -xOf "$tarball" package/package.json 2>/dev/null | node -e '
    let input = "";
    process.stdin.on("data", chunk => input += chunk);
    process.stdin.on("end", () => {
      try { process.stdout.write(JSON.parse(input).name || ""); }
      catch { process.exit(1); }
    });
  '
}

verify_fork_server_package() {
  local prefix="$1" server_tarball="$2"
  local installed_pkg packed_json installed_json
  installed_pkg="$(prefix_server_package_path "$prefix" || true)"
  if [ -z "$installed_pkg" ]; then
    die "Required fork server package @paperclipai/server is missing under $prefix. Aborting before migrations or cutover."
  fi
  if [ ! -f "$server_tarball" ]; then
    die "Required packed fork server tarball is missing: $server_tarball"
  fi
  packed_json="$(tar -xOf "$server_tarball" package/package.json 2>/dev/null)" \
    || die "Cannot read package/package.json from fork server tarball $server_tarball"
  installed_json="$(cat "$installed_pkg")"
  if ! node -e '
    const packed = JSON.parse(process.argv[1]);
    const installed = JSON.parse(process.argv[2]);
    if (packed.name !== "@paperclipai/server" || installed.name !== packed.name || installed.version !== packed.version) process.exit(1);
    if (JSON.stringify(installed) !== JSON.stringify(packed)) process.exit(1);
  ' "$packed_json" "$installed_json"; then
    die "Installed fork server package does not match produced workspace tarball $server_tarball. Aborting before migrations or cutover."
  fi
  verify_packed_runner_binary "$prefix" "$server_tarball" "$installed_pkg"
  log "Verified fork server package $installed_pkg matches produced workspace tarball $server_tarball"
}

file_sha256() {
  node -e '
    const fs = require("fs");
    const crypto = require("crypto");
    const hash = crypto.createHash("sha256");
    hash.update(fs.readFileSync(process.argv[1]));
    process.stdout.write(hash.digest("hex"));
  ' "$1"
}

file_mode() {
  node -e 'process.stdout.write((require("fs").statSync(process.argv[1]).mode & 0o777).toString(8))' "$1"
}

verify_packed_runner_binary() (
  local prefix="$1" server_tarball="$2" installed_pkg="$3"
  local scratch packed_runner installed_runner
  scratch="$(mktemp -d "${TMPDIR:-/tmp}/paperclip-runner-verify.XXXXXX")"
  trap 'rm -rf "$scratch"' EXIT
  packed_runner="$scratch/package/dist/vendor/paperclip-runner/bin/paperclip-runnerd"
  installed_runner="$(dirname "$installed_pkg")/dist/vendor/paperclip-runner/bin/paperclip-runnerd"
  tar -xzf "$server_tarball" -C "$scratch" package/dist/vendor/paperclip-runner/bin/paperclip-runnerd 2>/dev/null \
    || die "Packed fork server has no paperclip-runnerd binary. Aborting before migrations or cutover."
  [ -f "$packed_runner" ] && [ ! -L "$packed_runner" ] && [ -s "$packed_runner" ] \
    || die "Packed fork server paperclip-runnerd binary is empty. Aborting before migrations or cutover."
  [ -f "$installed_runner" ] && [ ! -L "$installed_runner" ] && [ -s "$installed_runner" ] \
    || die "Installed fork server paperclip-runnerd binary is missing or empty. Aborting before migrations or cutover."
  chmod 0755 "$installed_runner" \
    || die "Cannot make installed fork server paperclip-runnerd executable. Aborting before migrations or cutover."
  [ "$(file_mode "$installed_runner")" = "755" ] \
    || die "Installed fork server paperclip-runnerd must have mode 0755. Aborting before migrations or cutover."
  [ -x "$installed_runner" ] \
    || die "Installed fork server paperclip-runnerd is not executable. Aborting before migrations or cutover."
  [ "$(file_sha256 "$packed_runner")" = "$(file_sha256 "$installed_runner")" ] \
    || die "Installed fork server runner binary hash mismatch against packed artifact. Aborting before migrations or cutover."
  log "Verified packed and installed paperclip-runnerd hashes and mode 0755"
)

current_target() {
  if [ -L "$CURRENT_LINK" ]; then
    readlink "$CURRENT_LINK"
  else
    echo ""
  fi
}

record_previous_target() {
  local target="$1"
  mkdir -p "$STATE_DIR"
  if [ -n "$target" ]; then
    printf '%s\n' "$target" > "$PREVIOUS_STATE_FILE"
    log "Recorded previous prefix for rollback: $target"
  fi
}

read_previous_target() {
  if [ -f "$PREVIOUS_STATE_FILE" ]; then
    cat "$PREVIOUS_STATE_FILE"
  else
    echo ""
  fi
}

flip_symlink() {
  local target="$1"
  # Always a real filesystem operation, even under PAPERCLIP_ENGINE_DRY_RUN=1
  # — it is local, cheap, and it IS the state this script (and its tests)
  # exist to exercise; unlike npm/git/systemctl/pg_dump it is never stubbed.
  # ln -sfn atomically replaces an existing symlink (rename() under the
  # hood) on both GNU and BSD/macOS ln — unlike `mv`, which has the
  # well-known "moves INTO an existing symlink-to-directory" gotcha.
  log "+ ln -sfn $target $CURRENT_LINK"
  ln -sfn "$target" "$CURRENT_LINK"
}

# ---------------------------------------------------------------------------
# systemd
# ---------------------------------------------------------------------------

unit_stop() {
  run systemctl --user stop "$UNIT_NAME" || true
}

# Returns non-zero (does not `die`) if the unit fails to reach "started" —
# with Type=notify this call blocks until sd_notify(READY=1) or a timeout,
# so a broken new version legitimately makes this fail. Callers MUST check
# the return value themselves (never call this bare under `set -e` and
# expect to reach a rollback branch afterwards — a non-zero exit here would
# otherwise abort the whole script before rollback logic runs).
#
# PAPERCLIP_ENGINE_TEST_FAIL_START=1 forces a synthetic failure, for tests
# that need to exercise the rollback path without a real unit.
unit_start() {
  if [ "${PAPERCLIP_ENGINE_TEST_FAIL_START:-0}" = "1" ]; then
    log "+TESTHOOK simulating systemctl start failure (PAPERCLIP_ENGINE_TEST_FAIL_START=1)"
    return 1
  fi
  run systemctl --user start "$UNIT_NAME"
}

unit_restart() {
  run systemctl --user restart "$UNIT_NAME"
}

unit_assert_compatible() {
  local unit_path="$HOME/.config/systemd/user/$UNIT_NAME"
  local template="$1"
  if [ -f "$unit_path" ] && ! cmp -s "$template" "$unit_path" && [ "${PAPERCLIP_ENGINE_REPLACE_UNIT:-0}" != "1" ]; then
    log "Existing unit file $unit_path differs from $template:"
    diff -u "$unit_path" "$template" >&2 || true
    die "Refusing to overwrite an existing, different unit file. Review the diff above; set PAPERCLIP_ENGINE_REPLACE_UNIT=1 to replace it deliberately."
  fi
}

valid_paperclip_prefix() {
  local prefix="$1"
  [ -f "$prefix/lib/node_modules/paperclipai/package.json" ] &&
    [ -x "$prefix/bin/paperclipai" ]
}

prepare_existing_prefix_adoption() {
  local adopted="$PAPERCLIP_ENGINE_ADOPT_EXISTING_PREFIX"
  [ -n "$adopted" ] || return 0

  case "$adopted" in
    /*) ;;
    *) die "PAPERCLIP_ENGINE_ADOPT_EXISTING_PREFIX must be an absolute npm prefix." ;;
  esac
  valid_paperclip_prefix "$adopted" \
    || die "Adopted prefix $adopted is not valid: require package.json and executable bin/paperclipai."

  local unit_path="$HOME/.config/systemd/user/$UNIT_NAME"
  [ -f "$unit_path" ] || die "Adoption requires existing unit $unit_path; refusing to create a second unit."

  if [ -L "$CURRENT_LINK" ]; then
    local target
    target="$(readlink "$CURRENT_LINK")"
    case "$target" in
      "$adopted"|"$ENGINE_ROOT"/paperclip-*) ;;
      *) die "Current link $CURRENT_LINK points outside the adopted or managed prefixes: $target" ;;
    esac
    valid_paperclip_prefix "$target" \
      || die "Current link target $target is not a valid Paperclip prefix."
  elif [ -e "$CURRENT_LINK" ]; then
    die "Current link path $CURRENT_LINK exists but is not a symlink."
  else
    mkdir -p "$(dirname "$CURRENT_LINK")"
    flip_symlink "$adopted"
    log "Seeded current link from adopted prefix: $CURRENT_LINK -> $adopted"
  fi

  local dropin_dir="$HOME/.config/systemd/user/$UNIT_NAME.d"
  local dropin_path="$dropin_dir/$ADOPTION_DROPIN_NAME"
  if [ "$DRY_RUN" = "1" ]; then
    log "+DRYRUN would ensure adoption drop-in $dropin_path for $CURRENT_LINK/bin/paperclipai"
    return 0
  fi

  mkdir -p "$dropin_dir"
  local tmp
  tmp="$(mktemp "$dropin_dir/.${ADOPTION_DROPIN_NAME}.XXXXXX")"
  printf '%s\n' \
    '[Service]' \
    'ExecStart=' \
    "ExecStart=\"$CURRENT_LINK/bin/paperclipai\" run --instance \"$PAPERCLIP_INSTANCE_ID\"" > "$tmp"
  chmod 0644 "$tmp"
  if [ -f "$dropin_path" ] && cmp -s "$tmp" "$dropin_path"; then
    rm -f "$tmp"
  else
    mv "$tmp" "$dropin_path"
  fi
  run systemctl --user daemon-reload

  local effective
  effective="$(systemctl --user show "$UNIT_NAME" --property=ExecStart --value)"
  case "$effective" in
    *"$CURRENT_LINK/bin/paperclipai"*" run "*) ;;
    *) die "Effective ExecStart for $UNIT_NAME does not use $CURRENT_LINK/bin/paperclipai run: $effective" ;;
  esac
  log "Verified effective ExecStart for $UNIT_NAME uses $CURRENT_LINK/bin/paperclipai"
}

# Refuses to silently overwrite a unit file that already exists with
# different content — another operator/script (e.g. leaf 2's own install)
# may have put a different ExecStart there. Set
# PAPERCLIP_ENGINE_REPLACE_UNIT=1 to allow an intentional overwrite. A
# missing unit file is always installed (first run is not a conflict).
unit_ensure_installed() {
  local unit_path="$HOME/.config/systemd/user/$UNIT_NAME"
  local template="$1"
  if [ -n "$PAPERCLIP_ENGINE_ADOPT_EXISTING_PREFIX" ]; then
    return 0
  fi
  unit_assert_compatible "$template"
  if [ "$DRY_RUN" = "1" ]; then
    log "+DRYRUN would ensure unit file at $unit_path from $template"
    return 0
  fi
  mkdir -p "$(dirname "$unit_path")"
  if [ ! -f "$unit_path" ]; then
    log "Installing unit file $unit_path"
    cp "$template" "$unit_path"
    run systemctl --user daemon-reload
    return 0
  fi
  if ! cmp -s "$template" "$unit_path"; then
    log "Replacing unit file $unit_path (PAPERCLIP_ENGINE_REPLACE_UNIT=1)"
    cp "$template" "$unit_path"
    run systemctl --user daemon-reload
  fi
}

# ---------------------------------------------------------------------------
# Health
# ---------------------------------------------------------------------------

# Polls GET <url>; returns 0 and prints the JSON body on success (HTTP 2xx and
# body.status == "ok"), returns 1 after HEALTH_TIMEOUT_SECS otherwise.
wait_for_health() {
  local url="$1"
  local deadline=$(( $(date +%s) + HEALTH_TIMEOUT_SECS ))
  local body
  while [ "$(date +%s)" -lt "$deadline" ]; do
    if body="$(curl -fsS -m 5 "$url" 2>/dev/null)"; then
      if node -e '
          let input = "";
          process.stdin.on("data", (d) => (input += d));
          process.stdin.on("end", () => {
            try {
              const parsed = JSON.parse(input);
              process.exit(parsed.status === "ok" ? 0 : 1);
            } catch {
              process.exit(1);
            }
          });
        ' <<<"$body"; then
        echo "$body"
        return 0
      fi
    fi
    sleep "$HEALTH_POLL_SECS"
  done
  return 1
}

# ---------------------------------------------------------------------------
# Database
# ---------------------------------------------------------------------------

migration_count() {
  local connection_string="$1"
  if [ "$DRY_RUN" = "1" ]; then
    echo "0"
    return 0
  fi
  secure_database_command "$connection_string" psql -tAc 'select count(*) from "drizzle"."__drizzle_migrations"' 2>/dev/null | tr -d ' '
}

agents_paused_count() {
  local connection_string="$1"
  if [ "$DRY_RUN" = "1" ]; then
    echo "0"
    return 0
  fi
  # agents.status = 'paused' is the canonical signal the server itself
  # checks (server/src/routes/companies.ts, agents.ts, issues.ts all query
  # eq(agentsTable.status, "paused")) — not paused_at, which the schema
  # (packages/db/src/schema/agents.ts) only documents as "when", not as the
  # source of truth for whether an agent is currently paused.
  secure_database_command "$connection_string" psql -tAc "select count(*) from agents where status = 'paused'" 2>/dev/null | tr -d ' '
}

backup_database() {
  local connection_string="$1"
  local label="$2"
  mkdir -p "$BACKUP_DIR"
  local ts
  ts="$(date -u +%Y%m%dT%H%M%SZ)"
  local dump_path="$BACKUP_DIR/${ts}-${label}.dump"
  if ! secure_database_command "$connection_string" pg_dump -Fc -f "$dump_path"; then
    die "Database backup failed; refusing to build, migrate, or cut over."
  fi
  if [ "$DRY_RUN" != "1" ]; then
    [ -s "$dump_path" ] \
      || die "Database backup is empty: $dump_path. Refusing to build, migrate, or cut over."
    if ! pg_restore --list "$dump_path" >/dev/null 2>&1; then
      die "Database backup is not a readable PostgreSQL archive: $dump_path. Refusing to build, migrate, or cut over."
    fi
  fi
  echo "$dump_path"
}

resolve_migration_artifact() {
  local prefix="$1"
  local hoisted="$prefix/lib/node_modules/@paperclipai/db/dist/migrate.js"
  local nested="$prefix/lib/node_modules/paperclipai/node_modules/@paperclipai/db/dist/migrate.js"
  local matches=()
  [ -f "$hoisted" ] && matches+=("$hoisted")
  [ -f "$nested" ] && matches+=("$nested")
  if [ "${#matches[@]}" -eq 0 ]; then
    die "Installed prefix $prefix has no installed @paperclipai/db migration artifact."
  fi
  if [ "${#matches[@]}" -ne 1 ]; then
    die "Installed prefix $prefix has ambiguous @paperclipai/db migration artifacts: ${matches[*]}"
  fi
  printf '%s\n' "${matches[0]}"
}

assert_overlay_zero_pending() {
  local candidate_prefix="$1" live_prefix="$2" connection_string="$3"
  local candidate_dir="$candidate_prefix/lib/node_modules/paperclipai/node_modules/@paperclipai/db/dist/migrations"
  local live_dir="$live_prefix/lib/node_modules/paperclipai/node_modules/@paperclipai/db/dist/migrations"
  [ -d "$candidate_dir" ] && [ -d "$live_dir" ] || die "Cannot prove zero pending migrations: migration directory missing."
  node -e '
    const fs=require("fs"),path=require("path"),crypto=require("crypto");
    function manifest(root){const out=[];function walk(d){for(const e of fs.readdirSync(d,{withFileTypes:true})){const p=path.join(d,e.name);if(e.isSymbolicLink())process.exit(4);if(e.isDirectory())walk(p);else if(e.isFile()){const b=fs.readFileSync(p);out.push([path.relative(root,p),b.length,crypto.createHash("sha256").update(b).digest("hex")]);}else process.exit(4)}}walk(root);return JSON.stringify(out.sort((a,b)=>a[0].localeCompare(b[0])))}
    if(manifest(process.argv[1])!==manifest(process.argv[2])) process.exit(3);
  ' "$candidate_dir" "$live_dir" || die "Candidate migration identity/hash manifest differs from live installed migrations; refusing cutover."
  local scratch candidate_ledger live_ledger
  scratch="$(mktemp -d "${TMPDIR:-/tmp}/paperclip-ledger.XXXXXX")"
  candidate_ledger="$scratch/candidate"; live_ledger="$scratch/live"
  trap 'rm -rf "$scratch"' RETURN
  node -e '
    const fs=require("fs"),path=require("path"),crypto=require("crypto");
    const root=process.argv[1], journal=JSON.parse(fs.readFileSync(path.join(root,"meta/_journal.json")));
    for(const e of journal.entries){const sql=fs.readFileSync(path.join(root,e.tag+".sql"));console.log(`${e.when}|${crypto.createHash("sha256").update(sql).digest("hex")}`)}
  ' "$candidate_dir" | LC_ALL=C sort > "$candidate_ledger" || die "Cannot derive candidate migration journal/hash ledger."
  live_migration_ledger "$connection_string" | LC_ALL=C sort > "$live_ledger" || die "Cannot read live migration ledger."
  [ "$(wc -l < "$candidate_ledger")" -eq 231 ] || die "Candidate journal must contain exactly 231 entries."
  [ "$(wc -l < "$live_ledger")" -eq 234 ] || die "Live migration ledger must contain exactly 234 rows."
  [ "$(comm -23 "$candidate_ledger" "$live_ledger" | wc -l)" -eq 0 ] || die "Candidate has migration journal entries absent from live ledger; pending migrations are forbidden."
  [ "$(comm -13 "$candidate_ledger" "$live_ledger" | wc -l)" -eq 3 ] || die "Live migration ledger must have exactly three historical surplus rows."
  rm -rf "$scratch"; trap - RETURN
  local migration_file_count
  migration_file_count="$(find "$candidate_dir" -type f | wc -l)"
  log "Verified zero pending migrations: exact ${migration_file_count}-file tree, 231 mapped journal rows, and 3 historical live rows"
}

live_migration_ledger() {
  secure_database_command "$1" psql -Atc "select created_at::text || '|' || hash from drizzle.__drizzle_migrations order by created_at, hash"
}
