#!/usr/bin/env python3
"""SPA-10294 - regenerate the guard enumeration as valid, quoted CSV.

Every field is passed through csv.writer, so commas and quotes inside a cell can
never shift the column boundary. A row whose column count does not match the
header is a defect in this audit's own file of record, and the reader below fails
closed on it.
"""
import csv
import sys

HEADER = [
    "guard_id",
    "surface",
    "file_line",
    "identity_keyed_on",
    "mechanism",
    "classification",
    "evidence_for_classification",
    "per_run_verdict",
]

TOL = "TOLERANT"
NEED = "NEEDS-PER-RUN-ADAPTATION"
EXEMPT = "MUST-BE-EXEMPTED"
SEE_G02 = "SEE-G02"

ROWS = [
    (
        "G01",
        "engine",
        "server/src/services/workspace-runtime.ts:2914-2989",
        "branch",
        "inspectManagedGitWorktreeBranch: realpath-resolve worktreePath, require registered in `git worktree list`, require `rev-parse --show-toplevel` == worktreePath, require `symbolic-ref HEAD` == expectedBranchName",
        TOL,
        "Behaviour is a pure function of (path, repoRoot, expectedBranchName); nothing reads process.cwd(). Exercised under two cwds in checks/neg-b-needs-change.ts case B-6 logic and by inspection at :2967-2980.",
        "unchanged-verdict",
    ),
    (
        "G02",
        "engine",
        "server/src/services/workspace-runtime.ts:3461-3472",
        "path",
        'path.relative(worktreeParentDir, worktreePath).startsWith("..") -> throw worktree_path_escapes_parent_dir',
        NEED,
        "runs/<runId> is joined FROM worktreeParentDir so path.relative is `runs/<runId>` and never starts with `..`; the guard still passes. It is a containment check with no run identity, so it cannot detect an escaping runIdSegment. The guard does not break; it is blind.",
        "guard-intact-but-blind-to-run-identity",
    ),
    (
        "G03",
        "engine",
        "server/src/services/workspace-runtime.ts:3672-3693",
        "branch",
        "findRegisteredGitWorktreeByBranch(repoRoot, branchName) returns the prior run's directory; reuseExistingWorktree returns the reused path",
        NEED,
        "Directory identity is per-run (wr.ts:3458-3460) but the registry is keyed on branch, which stays per-card. Run N+1 of a dirty card resolves run N's directory. Pre-change failure demonstrated by checks/neg-b-needs-change.ts case B-1.",
        "isolation-degrades-to-reuse",
    ),
    (
        "G04",
        "engine",
        "server/src/services/workspace-runtime.ts:4415-4455",
        "branch+sha",
        "deleteGitBranchAtVerifiedTip: writes a detached HEAD at expectedHeadSha, then `git branch -d`",
        NEED,
        "Cleanup deletes workspace.branchName. Under the flag the per-run worktree owns that branch; deleting it from a detached HEAD sidesteps the worktree lock but destroys a per-run branch still checked out by another concurrent run. Intent (delete only the verified tip) survives; the mechanism must become run-scoped and refuse while a live worktree still has the branch checked out.",
        "pre-change-deletes-live-per-run-branch",
    ),
    (
        "G05",
        "engine",
        "server/src/services/workspace-runtime.ts:4684-4694",
        "path",
        "containsProjectWorkspace: containment of projectWorkspaceCwd inside path.resolve(workspacePath)",
        TOL,
        "Exercised against two synthetic cwds in checks/neg-a-tolerant-g05.ts: identical verdict under both, and the positive control still refuses. Direction is unchanged because runs/<runId> is strictly inside the parent dir.",
        "unchanged-verdict",
    ),
    (
        "G06",
        "engine",
        "server/src/services/workspace-runtime.ts:5325-5327",
        "path-shape",
        'basename(dirname(workspacePath)) === "runs" -> live-run guard applies; else the literal "legacy"',
        EXEMPT,
        "The sweep treats every non-runs path as having no run identity. Under the flag, G03's reuse path hands back a per-CARD path while ephemeralLifecycle is true, so the shape test says legacy, runIdSegment becomes the string `legacy`, and the live-run gate cannot protect it. No single intent survives: the in-file comment claims the legacy shape has no run-id component, which is false for the ephemeral+reuse combination. Demonstrated by case B-3.",
        "identity-cannot-hold-per-run-here",
    ),
    (
        "G07",
        "engine",
        "server/src/services/workspace-instance-cleanup.ts:225-231",
        "instance-id",
        "INSTANCE_ID_RE + instanceId !== expectedInstanceId -> refuse instance cleanup",
        EXEMPT,
        "expectedInstanceId derives from workspace.metadata[WORKTREE_INSTANCE_ROOT_METADATA_KEY] (wr.ts:4605-4608). Per-run worktrees minted by PR #108 carry no such per-run metadata, so every ephemeral worktree falls to the refusal branch and instance artifacts are never reclaimed: an unbounded growth axis the flag creates. The id-mismatch intent (never delete another workspace's instance) is correct; its identity must become the run's own instance id, not a card-scoped one.",
        "pre-change-refuses-all-ephemeral-cleanup",
    ),
    (
        "G08",
        "engine",
        "server/src/services/workspace-runtime.ts:1527-1529",
        "branch",
        "registeredBranchRef === actualBranchRef inside branch-incoherence evidence",
        NEED,
        "Registered-vs-HEAD equality decides incoherence. Correct as written, but evaluated only on the reuse path, so under the flag it cannot answer whether the registry entry belongs to THIS run. That is G03 seen from the evidence builder.",
        "identity-key-must-gain-run-dimension",
    ),
    (
        "G09",
        "engine",
        "server/src/services/heartbeat.ts:3522-3536",
        "branch",
        "pre-dispatch inspectManagedGitWorktreeBranch then fail(git_worktree_branch_mismatch)",
        TOL,
        "Runs at the top of every run against the run's OWN realized worktreePath and branchName (heartbeat.ts:3513-3521); a per-run cwd is exactly what it is handed. A per-run worktree that is internally consistent raises nothing.",
        "unchanged-verdict",
    ),
    (
        "G10",
        "engine",
        "server/src/services/heartbeat.ts:22530-22543",
        "path-shape",
        "two shape tests inferring ephemeral-ness from worktreePath shape rather than the persisted flag",
        EXEMPT,
        "Both tests read path shape. The startsWith form is `.paperclip/worktrees/runs`-prefixed and never matches the configured /srv/bulk worktreeParentDir, so the basename(dirname()) === 'runs' test is the one that fires. Under G03's reuse path the worktreePath is a per-CARD path while ephemeralLifecycle is true, so the shape test disagrees with the persisted flag and the cleanup branch silently does not fire.",
        "shape-inference-contradicts-persisted-flag",
    ),
    (
        "G11",
        "engine",
        "server/src/services/heartbeat.ts:3072 and 24539",
        "branch",
        "git_worktree_branch_incoherence raise sites",
        TOL,
        "Both consume inspectManagedGitWorktreeBranch (G01) output for the run's own worktree; neither assumes a cwd. A per-run cwd that is internally consistent raises nothing.",
        "unchanged-verdict",
    ),
    (
        "G12",
        "engine",
        "server/src/services/workspace-runtime.ts:4565",
        "recorder-field",
        "cwd: workspacePath ?? input.projectWorkspace?.cwd ?? process.cwd() on a teardown recorder",
        TOL,
        "process.cwd() is reached only when both workspacePath and projectWorkspace.cwd are absent; the value is a log field, never an identity decision, and on the git_worktree path the first operand is always set.",
        "unchanged-verdict",
    ),
    (
        "G13",
        "engine",
        "server/src/services/workspace-runtime.ts:4701",
        "recorder-field",
        "cwd: projectWorkspaceCwd ?? process.cwd() on a remove_local_fs recorder",
        TOL,
        "Same shape as G12; recorder field only.",
        "unchanged-verdict",
    ),
    (
        "G14",
        "engine",
        "server/src/services/workspace-runtime.ts:3042-3045",
        "path",
        "buildWorkspaceCommandEnv sets PAPERCLIP_WORKSPACE_CWD / _PATH / _WORKTREE_PATH = worktreePath and _BRANCH = branchName",
        TOL,
        "Publishes the run's own realized values every run; no comparison against a remembered value. Consumers must read it rather than assume it, which is what rows G15, G21, G28 do.",
        "unchanged-verdict",
    ),
    (
        "G15",
        "engine",
        "server/src/services/native-runtime/native-session-executor.ts:508-510",
        "path",
        "buildNativeProviderEnvironment: environment.PAPERCLIP_WORKSPACE_CWD = assignedWorkspaceCwd, described in-file as an immutable containment boundary",
        TOL,
        "Sets the value, never compares. Its consumer (G16) is relative to this value, so the pair is cwd-agnostic. Exercised under two cwds by case B-6.",
        "unchanged-verdict",
    ),
    (
        "G16",
        "engine",
        "packages/paperclip-runner/src/drivers/codex/codex-boundaries.ts:71-120",
        "path",
        "configuredRoot := PAPERCLIP_WORKSPACE_CWD; resolved cwd must be inside root, must not contain HOME or CODEX_HOME, must not be a filesystem root",
        TOL,
        "Pure path containment relative to the configured root; runs/<runId> is inside the root by construction. Case B-6 runs it under two roots and still rejects an outside path, which is the control's deliberate counter-example: a tolerant guard that must NOT appear in the failure set.",
        "unchanged-verdict",
    ),
    (
        "G17",
        "engine",
        "server/src/services/workspace-git-operation-scheduler.ts:214-247",
        "path",
        "workspaceIdentity + scanKey hash the canonical workspace path; per-path queueing and cache",
        TOL,
        "Per-path identity means a per-run cwd gets its own queue slot and its own cache key. No cross-run coherence is asserted anywhere in the file, so a moving path cannot invalidate a held lock.",
        "unchanged-verdict",
    ),
    (
        "G18",
        "engine",
        "server/src/services/native-runtime/native-workspace-finalizer.ts:97, 110, 217-240",
        "path",
        "workspace?.providerRef ?? workspace?.cwd ?? previous?.cwd ?? null, then inspectManagedGitWorktreeBranch",
        EXEMPT,
        "This is the previous?.cwd FALLBACK. Under the flag the finalizer runs after the per-run directory is already removed, so providerRef/cwd can be empty and it silently falls back to the PREVIOUS run's directory and finalizes that. Under a per-card cwd the previous value was the same path, so the fallback was harmless. Demonstrated by case B-4; mutant B2 (the fix) inverts the control.",
        "pre-change-finalizes-previous-run",
    ),
    (
        "G19",
        "engine",
        "server/src/services/native-runtime/native-chat-workspace.ts:98-113",
        "path+status",
        "nativeChatWorkspaceCwd reuse gate requires providerRef === cwd and status in [active, idle]",
        TOL,
        "All predicates are about the workspace ROW, not a path identity; a per-run row satisfies them independently. The chat taskRoot derives from the issue id, never from a cwd.",
        "unchanged-verdict",
    ),
    (
        "G20",
        "engine",
        "server/src/services/workspace-runtime.ts:3461 (cross-listed with G02)",
        "path",
        "parent-dir containment coexisting with the branch-keyed registry",
        SEE_G02,
        "Cross-listed so the one-row-per-guard rule leaves neither bucket unclassified. The escape guard is tolerant of the runs/ shape; the registry it coexists with is not. Recorded under G02 as well; this row carries no independent verdict.",
        "see-G02",
    ),
    (
        "G21",
        "sparkmojo-paperclip-skill",
        "skills/machine-forks/sparkmojo-paperclip/SKILL.md:528 (template v40)",
        "branch",
        "`git branch --show-current` is your first move; if it does not match the card's branch, STOP",
        TOL,
        "The guard asserts branch equality, not path equality. The branch stays per-card under the flag (identity 1, wr.ts:3436-3443), so the guard's premise is unchanged.",
        "unchanged-verdict",
    ),
    (
        "G22",
        "sparkmojo-paperclip-skill",
        "skills/machine-forks/sparkmojo-paperclip/SKILL.md:529",
        "repo",
        "assert `git rev-parse --show-toplevel` is the assigned workspace; never write into a sibling checkout",
        TOL,
        "Asserts the repo TOP LEVEL, not a remembered directory. All runs of a card are worktrees of one repo, so the top level is stable across per-run cwds. The sibling-checkout hazard it prevents (DECISION-161 §161-9) is unaffected.",
        "unchanged-verdict",
    ),
    (
        "G23",
        "sparkmojo-paperclip-skill",
        "skills/machine-forks/sparkmojo-paperclip/SKILL.md:530",
        "path",
        "side work via `git worktree add ../<new-dir> -b <new-branch> refs/remotes/origin/main`; never `git checkout` inside the existing worktree",
        NEED,
        "The rule is right; its mechanism is path-relative. From a per-run cwd, `../<new-dir>` resolves to a sibling of the ephemeral runs/<runId> directory, i.e. the parent-dir level, not a sibling of the card worktree. Still correct and still outside the managed set, but it now creates worktrees that the /runs/ shape test (G06) does not recognise.",
        "still-correct-new-path-needs-enumeration",
    ),
    (
        "G24",
        "sparkmojo-paperclip-skill",
        "skills/machine-forks/sparkmojo-paperclip/SKILL.md:531",
        "path",
        "never create a git worktree or keep uncommitted work under $PAPERCLIP_RUN_SCRATCH_DIR / $PAPERCLIP_SCRATCH_DIR",
        TOL,
        "The scratch dir is run-scoped and orthogonal to the worktree location; the rule's premise (run teardown deletes it, SPA-9262) is unchanged.",
        "unchanged-verdict",
    ),
    (
        "G25",
        "sparkmojo-paperclip-skill",
        "skills/machine-forks/sparkmojo-paperclip/SKILL.md:533",
        "path",
        "arrive in a wrong-branch worktree: stop without changing, replacing, or removing it; route the defect",
        TOL,
        "Failure-path only. A per-run cwd makes a wrong-branch worktree strictly less likely, never more.",
        "unchanged-verdict",
    ),
    (
        "G26",
        "fleet-skill",
        "skills/sm-sessions/sm-build-paperclip/SKILL.md:87-91",
        "branch+repo",
        "`git branch --show-current`; `git worktree list` to confirm registered; assert `git rev-parse --show-toplevel` is the workspace",
        TOL,
        "Two of the three checks are branch/repo-scoped and therefore stable. `git worktree list` confirms registration, and a per-run worktree is registered, so the check still passes. No check compares against a remembered directory.",
        "unchanged-verdict",
    ),
    (
        "G27",
        "fleet-skill",
        "skills/sm-sessions/sm-build-paperclip/SKILL.md:26-29",
        "workspace",
        "consume the assigned native workspace; never create, repair, substitute, or remove a worktree",
        TOL,
        "A prohibition, not a comparison. Under the flag the assigned workspace is still engine-allocated.",
        "unchanged-verdict",
    ),
    (
        "G28",
        "fleet-skill",
        "skills/sm-sessions/sm-verify-paperclip/SKILL.md:321-322 and 402",
        "branch",
        'fallback <head> read from `git -C "$PAPERCLIP_WORKSPACE_CWD" branch --show-current`',
        TOL,
        "The -C argument is read from the env var the engine sets per run (G14), and it reads a BRANCH. Under the flag both the env var and the branch are per-run-correct.",
        "unchanged-verdict",
    ),
    (
        "G29",
        "fleet-skill",
        "skills/sm-sessions/sm-verify-paperclip/SKILL.md:328-330",
        "repo",
        'derive <repo> from `git -C "$PAPERCLIP_WORKSPACE_CWD" remote get-url origin`',
        TOL,
        "Repo-identity derivation, not directory identity; the origin remote is a property of the worktree's shared repo and is constant across per-run cwds.",
        "unchanged-verdict",
    ),
    (
        "G30",
        "fleet-skill",
        "skills/machine-forks/create-project/SKILL.md:60",
        "path",
        'teardownCommand: `git worktree remove "$PAPERCLIP_WORKSPACE_CWD" || true`',
        NEED,
        "The command reads the env var, so it is cwd-correct. But `|| true` swallows failure, and `git worktree remove` on a per-run directory races the engine's own force-removal at terminal status. Two removers on one per-run path is the new hazard; the intent (never leak worktrees) survives and the mechanism needs a per-run-aware teardown.",
        "double-remover-race",
    ),
    (
        "G31",
        "adapter-opencode-local",
        "packages/adapters/opencode-local/src/server/execute.ts:531-546",
        "path+sessionId",
        "canResumeSession requires path.resolve(runtimeSessionCwd) === path.resolve(effectiveExecutionCwd), else start fresh and log it",
        TOL,
        "A cwd inequality already degrades to a fresh session WITH an explicit log line at :544. Under the flag every run after the first logs that line and starts fresh. The cost is lost context, not a wrong-context resume. Exercised by the tolerance logic in case B-6.",
        "unchanged-verdict-cost-is-lost-context",
    ),
    (
        "G32",
        "adapter-opencode-local",
        "packages/adapters/opencode-local/src/server/execute.ts:548-559",
        "path",
        "instructionsFilePath resolved against cwd, then a directive telling the model to resolve relative references from instructionsDir",
        TOL,
        "Resolution is cwd-relative by construction and the resolved ABSOLUTE path is injected into the prompt at :559, so relative references follow the new cwd correctly. This is the fix pattern the fleet skills should copy (cf. incident I-3, bare-filename atom).",
        "unchanged-verdict",
    ),
    (
        "G33",
        "adapter-opencode-local",
        "packages/adapters/opencode-local/src/server/execute.ts:258-263",
        "path",
        "cwd = effectiveWorkspaceCwd || configuredCwd || process.cwd(); ensureAbsoluteDirectory(cwd, { createIfMissing: true })",
        TOL,
        "The engine always supplies workspaceCwd, so process.cwd() is unreachable on the git_worktree path; and the mkdir is idempotent for a fresh per-run directory.",
        "unchanged-verdict",
    ),
    (
        "G34",
        "adapter-opencode-local",
        "packages/adapters/opencode-local/src/server/models.ts:119-130 and 222-230",
        "path",
        "discoveryCacheKey hashes command + cwd + non-volatile env",
        TOL,
        "A per-run cwd means a per-run cache key, so model discovery re-runs per run instead of being reused. Correct, slightly more expensive, never a wrong result.",
        "unchanged-verdict-cost-is-redundant-discovery",
    ),
    (
        "G35",
        "adapter-opencode-local",
        "packages/adapters/opencode-local/src/server/models.ts:147 and 239",
        "path",
        "asString(input.cwd, process.cwd()) for model discovery",
        TOL,
        "A caller-supplied cwd wins; the fallback is reached only by a control-plane call with no workspace, which is not the run path.",
        "unchanged-verdict",
    ),
    (
        "G36",
        "adapter-opencode-local",
        "packages/adapter-utils/src/server-utils.ts:3289-3296",
        "path",
        "hint.cwd === localWorkspaceCwd -> repoint at realizedWorkspaceCwd",
        NEED,
        "Correct today. Under the flag both operands of the sibling-repo test at :3297-3301 (path.relative(localWorkspaceCwd, hintCwd)) move per run, so the relative form still matches. What needs re-verification is upstream: hints are minted by the engine from the run's own realization, and this row must be re-checked against that mint site once the flag ships.",
        "reverify-against-mint-site",
    ),
    (
        "G37",
        "adapter-opencode-local",
        "packages/adapter-utils/src/server-utils.ts:3364-3370",
        "path",
        "rewriteWorkspaceCwdEnvVarsForExecution: rewrite any *_WORKSPACE_CWD var equal to the local cwd to the remote cwd",
        TOL,
        "Self-referential comparison against the same variable the engine set for this run; both sides move together, so the rewrite can never miss.",
        "unchanged-verdict",
    ),
    (
        "G38",
        "adapter-opencode-local",
        "packages/adapter-utils/src/server-utils.ts:3241-3281",
        "path",
        "local target returns workspaceCwd verbatim; remote target substitutes executionCwd and warns on null",
        TOL,
        "The remote substitution exists precisely so a differing local/remote cwd cannot leak a host path. Under the flag the local cwd differs per run and the substitution follows it.",
        "unchanged-verdict",
    ),
    (
        "G39",
        "adapter-opencode-local",
        "packages/adapter-utils/src/execution-target.ts:1633",
        "repo",
        "fs.realpathSync(top) === fs.realpathSync(process.cwd()) -> export PAPERCLIP_GIT_METADATA_ROOTS",
        TOL,
        "Engine-host-side: the adapter server's OWN cwd, not the agent's workspace cwd. A per-run agent workspace does not change it, and the surrounding try/catch is fail-open by design.",
        "unchanged-verdict",
    ),
    (
        "G40",
        "adapter-opencode-local",
        "packages/adapter-utils/src/execution-target.ts:3097 and 3188",
        "path",
        "spawn cwd: config.cwd || process.cwd()",
        TOL,
        "Wrapper-emission path (process adapter) where config.cwd is the caller-supplied target; no workspace identity is asserted.",
        "unchanged-verdict",
    ),
    (
        "G41",
        "adapter-opencode-local",
        "scripts/provision-worktree.sh:5-6 and 19-31",
        "path+branch",
        "worktree_cwd from PAPERCLIP_WORKSPACE_CWD; worktree_name from PAPERCLIP_WORKSPACE_BRANCH or basename(worktree_cwd); worktree_instance_id = normalized basename + sha256(resolved workspace path)[0:12]",
        EXEMPT,
        "The instance id is derived from the DIRECTORY PATH. Under the flag the directory is runs/<runId>, so every run mints a NEW instance id, a new instance root, a new embedded Postgres data dir, new ports and a new master key (write_fallback_worktree_config). Per-run instance identity cannot be provisioned this way: the card's durable instance is the unit that G07's pointer cleanup reasons about. Demonstrated by case B-5.",
        "pre-change-per-run-instance-mint",
    ),
    (
        "G42",
        "adapter-opencode-local",
        "scripts/provision-worktree.sh:250-290 (existing_worktree_config_is_usable)",
        "path",
        "the worktree's own .paperclip/.env must point at the worktree's own .paperclip/config.json; instance id must match WORKTREE_INSTANCE_ID",
        EXEMPT,
        "The self-heal check holds per run because the directory is fresh, so it is trivially true and never exercises the cross-run drift it was written for (a worktree whose env still names a prior instance). Not a live failure - a guard that has stopped guarding, which the card's rule about weakening guards treats as worse than the meltdown.",
        "guard-becomes-vacuous",
    ),
    (
        "G43",
        "adapter-opencode-local",
        "scripts/provision-worktree.sh:compute_pnpm_install_fingerprint and the node_modules relink block",
        "path",
        "install fingerprint stored under the worktree's own .paperclip dir, compared to a hash of that worktree's package.json + pnpm-lock.yaml + patch manifest; node_modules relinked from the base workspace",
        NEED,
        "A full `pnpm install --prod=false` plus node_modules relink per run. Intent (a run has working node_modules) survives; the mechanism must consult a cache shared by the card's runs instead of a per-run one, or the flip trades disk growth for an install storm.",
        "per-run-install-storm",
    ),
    (
        "G44",
        "fleet-skill",
        "spark-mojo-platform scripts/machine/worktree_gc.py:415-434 (platform ref e50382dd7)",
        "path",
        'walk only roots ending "/.paperclip/worktrees"; consider immediate child dirs only; path_ok requires os.path.dirname(full) == worktrees_dir',
        EXEMPT,
        "Immediate-children-only plus the exact dirname equality means the runs/ subdirectory is never entered and every ephemeral worktree is invisible to GC. The capacity model the flag exists to serve depends on this sweeper. Pre-change behaviour proven by case B-2; mutant B4 (the fix) inverts the control.",
        "pre-change-gc-cannot-see-runs-dir",
    ),
    (
        "G45",
        "fleet-skill",
        "spark-mojo-platform scripts/machine/worktree_gc.py:73-76 and 425-427",
        "path",
        "BASE default and the by_cwd lookup keyed on the execution_workspaces.cwd column",
        TOL,
        "DB-row-keyed, so a per-run cwd row is looked up correctly. The failure is coverage (G44), not the lookup.",
        "unchanged-verdict",
    ),
    (
        "G46",
        "fleet-skill",
        "spark-mojo-platform scripts/ci/pin-validate.sh:84-85 and scripts/verify/check-root-gates-files.sh:85",
        "repo",
        "git rev-parse --show-toplevel, then cd to it",
        TOL,
        "CI runs in a checkout it chooses; the repo top level is stable across per-run cwds of the same repo.",
        "unchanged-verdict",
    ),
    (
        "G47",
        "fleet-skill",
        "spark-mojo-platform scripts/verify/check-root-gates-files.sh:95-100",
        "path",
        "is_forbidden_root_gates matches ^GATES.md$ / ^GATES-[^/]*.md$ on top-level-anchored --name-status paths",
        TOL,
        "RECLASSIFIED from needs-change. Top-level anchoring is relative to the resolved repo root, which does not move under the flag; the rule still forces the ledger into .unlazy/<CARD-ID>/gates.md. Recorded tolerant so the audit is not read as claiming uniform breakage - and the reclassification is recorded because a silent correction would have been an unsourced claim.",
        "unchanged-verdict",
    ),
    (
        "G48",
        "fleet-skill",
        "platform/AGENT_CONTEXT.md card-worktree branch rule (fleet-context render, SPA-8969)",
        "path",
        "never checkout/switch/reset inside the engine-allocated worktree; side work via `git worktree add ../<new-dir> -b <new-branch> refs/remotes/origin/main`",
        NEED,
        "Same mechanism as G23, in the file every agent reads at wake. `../<new-dir>` from a per-run cwd lands at the parent-dir level, outside the /runs/ set the engine sweeps. Intent survives; the documented example path must be restated for a per-run cwd.",
        "same-change-as-G23",
    ),
    (
        "G49",
        "fleet-skill",
        "platform/AGENT_CONTEXT.md DECISION-138 exit assertion (fleet laws v12)",
        "path",
        "four-predicate git hygiene block (not-in-work-tree, tree-dirty, detached-HEAD, ahead-of-remote) run in the run's own worktree",
        TOL,
        "DECISION-138 §138-5 makes predicates 1-4 apply in full to a per-run worktree because it authors a tree. None of the four predicates reads a remembered path; they read the tree the run produced. This very card's ledger passed the block under a harness-allocated worktree.",
        "unchanged-verdict",
    ),
    (
        "G50",
        "fleet-skill",
        "skills/sm-sessions/{sm-plan,sm-spec,sm-intake,sm-research-preflight,sm-plan-paperclip}/SKILL.md",
        "branch",
        "git branch --show-current; plan/spec/intake on a feature branch, never main",
        TOL,
        "Branch-scoped assertion of a branch that stays per-card (identity 1).",
        "unchanged-verdict",
    ),
]


def main() -> int:
    with open("docs/audits/SPA-10294-guard-enumeration.csv", "w", newline="", encoding="utf-8") as fh:
        writer = csv.writer(fh, quoting=csv.QUOTE_MINIMAL)
        writer.writerow(HEADER)
        for row in ROWS:
            assert len(row) == len(HEADER), f"{row[0]}: {len(row)} fields, expected {len(HEADER)}"
            writer.writerow(row)
    print(f"wrote {len(ROWS)} rows")
    return 0


if __name__ == "__main__":
    sys.exit(main())